mod ast;
mod logics;

use std::path::{Path, PathBuf};

use color_eyre::Result;

mod flags {
    xflags::xflags! {
        // src "./xtask/src/main.rs"

        cmd xtask {
            /// Generate the ast from the SMT-LIB standard
            cmd ast {}
            cmd logics {}
        }
    }
}

fn main() -> Result<()> {
    color_eyre::install()?;

    let sh = xshell::Shell::new()?;
    sh.change_dir(project_root());

    let e = flags::Xtask::from_env_or_exit();
    match e.subcommand {
        flags::XtaskCmd::Ast(_) => {
            let output = add_preamble("cargo xtask ast", ast::generate()?);
            sh.write_file("./lowlevel/src/ast.rs", output)?;
        }
        flags::XtaskCmd::Logics(_) => {
            let output = add_preamble("cargo xtask logics", logics::generate(&sh)?);
            sh.write_file("./smtlib/src/logics.rs", output)?;
        }
    }

    Ok(())
}

fn add_preamble(generator: &'static str, mut text: String) -> String {
    let mut preamble = format!("//! Generated by `{generator}`, do not edit by hand.\n");
    preamble += "#![allow(clippy::uninlined_format_args)]\n\n";
    text.insert_str(0, &preamble);
    text
}

fn project_root() -> PathBuf {
    Path::new(&env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(1)
        .unwrap()
        .to_path_buf()
}
