mod ast;
mod logics;

use std::path::{Path, PathBuf};

use color_eyre::{eyre::bail, Result};

mod flags {
    xflags::xflags! {
        // src "./xtask/src/main.rs"

        cmd xtask {
            /// Generate the ast from the SMT-LIB standard
            cmd ast {
                /// Check that the existing content matches the generated (does not write)
                optional --check
            }
            cmd logics {
                /// Check that the existing content matches the generated (does not write)
                optional --check
            }
        }
    }
}

const AST_PATH: &str = "./lowlevel/src/ast.rs";
const LOGICS_PATH: &str = "./smtlib/src/logics.rs";

fn main() -> Result<()> {
    color_eyre::install()?;

    let sh = xshell::Shell::new()?;
    sh.change_dir(project_root());

    let e = flags::Xtask::from_env_or_exit();
    match e.subcommand {
        flags::XtaskCmd::Ast(args) => {
            let output = add_preamble("cargo xtask ast", ast::generate()?);
            write_or_check(&sh, AST_PATH, args.check, &output)?;
        }
        flags::XtaskCmd::Logics(args) => {
            let output = add_preamble("cargo xtask logics", logics::generate(&sh)?);
            write_or_check(&sh, LOGICS_PATH, args.check, &output)?;
        }
    }

    Ok(())
}

fn write_or_check(
    sh: &xshell::Shell,
    path: impl AsRef<Path>,
    check: bool,
    content: &str,
) -> Result<()> {
    let path = path.as_ref();

    if check {
        let previous = sh.read_file(path)?;

        if content == previous {
            Ok(())
        } else {
            bail!(
                "generated `{}` does not match contents on disk",
                path.display()
            )
        }
    } else {
        sh.write_file(path, content)?;
        Ok(())
    }
}

fn add_preamble(generator: &'static str, mut text: String) -> String {
    let mut preamble = format!("//! Generated by `{generator}`, do not edit by hand.\n");
    preamble += "#![allow(clippy::uninlined_format_args)]\n\n";
    text.insert_str(0, &preamble);
    text
}

fn project_root() -> PathBuf {
    Path::new(&env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(1)
        .unwrap()
        .to_path_buf()
}
